lead/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from lead.views import (
    Index,
    UserCreateView,
    login_view,
)

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("users/create/", UserCreateView.as_view(), name="user-create"),
    path('login/', login_view, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

app_name = "lead"

lead_generator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("lead.urls", namespace="lead")),
    path("accounts/", include("django.contrib.auth.urls")),
]

lead/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):

    class Meta:
        verbose_name = "user"
        verbose_name_plural = "users"

    def __str__(self) -> str:
        return f"{self.username} {self.email}"

lead/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from lead.models import User


class LeadForm(forms.Form):
    number_choices = (
        ('Ten', 10),
        ('Twenty', 20),
        ('Thirty', 30),
    )

    keywords = forms.CharField(label="Keywords: ")
    location = forms.CharField(label="Locations: ")
    leads_num = forms.IntegerField(label="Leads num: ", widget=forms.Select(choices=number_choices))


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Email",
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password check",
                "class": "form-control"
            }
        ))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

lead/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from lead.forms import LeadForm, SignUpForm, LoginForm
from lead.models import User


class Index(LoginRequiredMixin, generic.FormView):
    form_class = LeadForm
    template_name = "index.html"


class UserCreateView(generic.CreateView):
    model = User
    form_class = SignUpForm
    template_name = "user_form.html"
    success_url = reverse_lazy("lead:index")


def login_view(request):
    form = LoginForm(request.POST or None)

    msg = None

    if request.method == "POST":

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("lead:index")
            else:
                msg = 'Invalid credentials'
        else:
            msg = 'Error validating the form'

    return render(request, "index.html")

lead/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous">

<title>
    Lead Generator
</title>

<link type="text/css" href="{{ ASSETS_ROOT }}/vendor/sweetalert2/dist/sweetalert2.min.css" rel="stylesheet">

<link type="text/css" href="{{ ASSETS_ROOT }}/vendor/notyf/notyf.min.css" rel="stylesheet">

<link type="text/css" href="{{ ASSETS_ROOT }}/css/volt.css" rel="stylesheet">

</head>
<body>

    <header class="header-global">
        <nav id="navbar-main" aria-label="Primary navigation" class="navbar navbar-main navbar-expand-lg navbar-theme-primary pt-4 navbar-dark">
            <div class="container position-relative">
                <div class="navbar-collapse collapse me-auto" id="navbar_global">
                    <div class="navbar-collapse-header">
                        <div class="row">
                            <div class="col-6 collapse-brand">
                                <a href="/">
                                    <img src="{{ ASSETS_ROOT }}/img/brand/light.svg" alt="Volt logo">
                                </a>
                            </div>
                            <div class="col-6 collapse-close">
                                <a href="#navbar_global" class="fas fa-times" data-toggle="collapse" data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false" title="close" aria-label="Toggle navigation"></a>
                            </div>
                        </div>
                    </div>
                    <ul class="navbar-nav navbar-nav-hover align-items-lg-center">

                        {% if user %}
                            <div class="d-flex align-items-center ms-auto text-white">
                                {{ user.username }}
                            </div>
                        {% endif %}
                    </ul>
                </div>
                <div class="d-flex align-items-center ms-auto">
                    <a href="{% url 'lead:user-create' %}"
                       class="btn btn-outline-white d-inline-flex align-items-center me-md-3">
                        Sign Up
                    </a>
                </div>
                <div class="d-flex align-items-center ms-auto">
                    <a href="{% url 'login' %}"
                       class="btn btn-outline-white d-inline-flex align-items-center me-md-3">
                        Login
                    </a>
                </div>
                <div class="d-flex align-items-center ms-auto">
                    <a href="{% url 'logout' %}"
                       class="btn btn-outline-white d-inline-flex align-items-center me-md-3">
                        Logout
                    </a>
                </div>

            </div>
        </nav>
    </header>

    <main>

        <section class="section-header overflow-hidden pt-7 pt-lg-8 pb-9 pb-lg-12 bg-primary text-white">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center">
                            <h1 class="fw-bolder">Lead Generator</h1>

                            <h2 class="lead fw-normal text-muted mb-5">
                                To get started, I need all the following information
                            </h2>

                        <div class="d-flex align-items-center justify-content-center mb-5">
                          {% block content %}{% endblock content %}

                        </div>
                        <div class="d-flex justify-content-center flex-column mb-6 mb-lg-5">
                                <span class="text-muted font-small">
                                    &copy; Chornyi Oleh
                                </span>

                            </a>
                        </div>
                    </div>
                </div>
            </div>

        </section>

    </main>

</body>
</html>

lead/templates/index.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

      <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <input type="submit" value="Submit" class="btn btn-primary">
      </form>
{% endblock %}

lead/templates/user_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="p-6">
    <h1>{{ object|yesno:"Update,Create" }} user</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <input type="submit" value="Submit" class="btn btn-primary">
    </form>
  </div>

{% endblock %}